NPM_PACKAGES="${HOME}/.npm-packages"

PATH="$NPM_PACKAGES/bin:$PATH"

export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$DIR/alias"
source "$DIR/ps1"
source "$DIR/git-completion.bash"

. "$DIR/z.sh"

# heroku autocomplete setup
HEROKU_AC_BASH_SETUP_PATH=/Users/miguel.almeida/Library/Caches/heroku/autocomplete/bash_setup && test -f $HEROKU_AC_BASH_SETUP_PATH && source $HEROKU_AC_BASH_SETUP_PATH;
